### ISSUE TITLE
'About' command does not work properly

### ISSUE THREAD

**Issue by ghost** [BeekeeperAlex/U413-archived#64]
TypeError: Object [object Object] has no method 'clearDisplay'

**Comment by BeekeeperAlex** [comment]
That method was from an older version of the [shotgun](http://github.com/chevex/shotgun) dependency. [Making those dependencies refer to static version numbers](https://github.com/chevex/U413/commit/b8a8295d4dbff1fe70c3544aee5381c34769c0e2#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R16) fixed the issue.
